# This file was generated by GoReleaser. DO NOT EDIT.
class Colout < Formula
  desc "A small and simple CLI tool that makes it easy to use colored output."
  homepage "https://github.com/kemokemo/colout"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kemokemo/colout/releases/download/v0.1.0/colout_darwin_x86_64.tar.gz"
    sha256 "bdc90899c9dd3cb865aa901edc1c869cb342474cefb41da2012946859d4c8c4b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/colout/releases/download/v0.1.0/colout_linux_x86_64.tar.gz"
      sha256 "f87fcac88ce62f7650155727faef4c35183437caebfc5ab115dc2d59002d4c77"
    end
  end

  def install
    bin.install "colout"
  end
end
