# This file was generated by GoReleaser. DO NOT EDIT.
class Colout < Formula
  desc "A small and simple CLI tool that makes it easy to use colored output."
  homepage "https://github.com/kemokemo/colout"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kemokemo/colout/releases/download/v0.1.0/colout_darwin_x86_64.tar.gz"
    sha256 "64c65257fe2222f31468e088c5eba622f8bfd37b9bfb0bacbdebafa2c9dba4c2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/colout/releases/download/v0.1.0/colout_linux_x86_64.tar.gz"
      sha256 "0af5bdcd67647d1c016cf3fe277924eccb47ae3adfdc236436f801dd3ac8bb13"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kemokemo/colout/releases/download/v0.1.0/colout_linux_arm64.tar.gz"
        sha256 "c1969c39d63e1692d46df18e090a76dc7f3945e8db09442940a4ace7cc9ce714"
      else
      end
    end
  end

  def install
    bin.install "colout"
  end
end
