# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Furit < Formula
  desc "This tool finds unreferenced images from text files such as markdown."
  homepage "https://github.com/kemokemo/furit"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.3/furit_Darwin_arm64.tar.gz"
      sha256 "45d5b44364aa6b0cfe8f6cdb33cad2c8e9b48e05a4f148c54ef650dea769e3f0"

      def install
        bin.install "furit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.3/furit_Darwin_x86_64.tar.gz"
      sha256 "299a261aea4e404381e4d3fceac6882a28681f52f7b35f86813838c58ae5567c"

      def install
        bin.install "furit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.3/furit_Linux_x86_64.tar.gz"
      sha256 "2f9063cd2597f9e22906e3149c23f8d9ae37953015b9038630af9d8565f0046a"

      def install
        bin.install "furit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.3/furit_Linux_arm64.tar.gz"
      sha256 "aac1f0e5b5375986ea9e9ab8895416510cc8862a87be282b48c554871a0d240b"

      def install
        bin.install "furit"
      end
    end
  end
end
