# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Furit < Formula
  desc "This tool finds unreferenced images from text files such as markdown."
  homepage "https://github.com/kemokemo/furit"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.1/furit_Darwin_arm64.tar.gz"
      sha256 "4391e1890c65450c6f40362ee8ae033e466e56285045e4db820112d521df9ef7"

      def install
        bin.install "furit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.1/furit_Darwin_x86_64.tar.gz"
      sha256 "e81ce0265ae65b865801f8af37ce6469507da01c4543baafc337c61e2c7c55d9"

      def install
        bin.install "furit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.1/furit_Linux_arm64.tar.gz"
      sha256 "cd442bb1b3626579827785fab831b1be64a8a1d452923d9091ef6a35146689d7"

      def install
        bin.install "furit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/furit/releases/download/v0.2.1/furit_Linux_x86_64.tar.gz"
      sha256 "b8d2a03f49f4cc041695e98c7072615f3a8835df5d540a8ba2f03b604ebe22ac"

      def install
        bin.install "furit"
      end
    end
  end
end
