# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gckdir < Formula
  desc "A tool to generate a hash list of specified directory and comapare it with the target directory."
  homepage "https://github.com/kemokemo/gckdir"
  version "0.7.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/gckdir/releases/download/v0.7.2/gckdir_Darwin_x86_64.tar.gz"
      sha256 "08eae3d2188d5ea60aa593dd4b3b3637c57c55fdbae6931ec83e391150fa4c8b"

      def install
        bin.install "gckdir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/gckdir/releases/download/v0.7.2/gckdir_Darwin_arm64.tar.gz"
      sha256 "5f848956e7909f8c8ad787efcc181af4e9bd351b8c4bae0c1347d845aba97060"

      def install
        bin.install "gckdir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/gckdir/releases/download/v0.7.2/gckdir_Linux_arm64.tar.gz"
      sha256 "fc4ed0a8c8dcf4cb89a2781ba670fcb83599e3b8c441bc37dc05f128a95ec292"

      def install
        bin.install "gckdir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/gckdir/releases/download/v0.7.2/gckdir_Linux_x86_64.tar.gz"
      sha256 "5c4280fe00f1f39276f29541c5a1f2844cc949cc6f76d4078be30a71df952061"

      def install
        bin.install "gckdir"
      end
    end
  end
end
