# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gfp < Formula
  desc "It's a simple and tiny tool to get a free port."
  homepage "https://github.com/kemokemo/gfp"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/gfp/releases/download/v0.1.0/gfp_Darwin_arm64.tar.gz"
      sha256 "19e948ba7e9c0b6ed9fdbc980cb5bc122ea7595b9123199e2e30e2d0cbb7198c"

      def install
        bin.install "gfp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/gfp/releases/download/v0.1.0/gfp_Darwin_x86_64.tar.gz"
      sha256 "5e7852b093583e3ba9518fc90d62d3b69b0c201095561a4c670c849a90873b06"

      def install
        bin.install "gfp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/gfp/releases/download/v0.1.0/gfp_Linux_x86_64.tar.gz"
      sha256 "781b9980b1d6e52ef1909c6cbe6981abf28e26047056e4f1c4afdbc0726cd2b2"

      def install
        bin.install "gfp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/gfp/releases/download/v0.1.0/gfp_Linux_arm64.tar.gz"
      sha256 "c874441df43c4bde9efb8bbafbae270b4830bac00f768842df3d3a4b6af692ad"

      def install
        bin.install "gfp"
      end
    end
  end
end
