# This file was generated by GoReleaser. DO NOT EDIT.
class Gomrepo < Formula
  desc "This small tool adds license information to the 'go module' information and outputs it in various formats."
  homepage "https://github.com/kemokemo/gomrepo"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kemokemo/gomrepo/releases/download/v0.1.0/gomrepo_Darwin_x86_64.tar.gz"
    sha256 "87495c233334b00ac7b7579a768741ba4d66e1a08b9f0e4d67bda297a08f9b7b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kemokemo/gomrepo/releases/download/v0.1.0/gomrepo_Linux_x86_64.tar.gz"
    sha256 "cb61240a1b91d29ce9c7d172b33ebfab333117b9573ecceb715c55f58612dbcd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kemokemo/gomrepo/releases/download/v0.1.0/gomrepo_Linux_arm64.tar.gz"
    sha256 "7812f4c82769a0307db787afc25d610f3ab1637fcc9307768007376238b347b4"
  end

  def install
    bin.install "gomrepo"
  end
end
