# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Htmldiff < Formula
  desc "This tool compares old and new versions of image files and generates color-coded image in a diff format."
  homepage "https://github.com/kemokemo/htmldiff"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/htmldiff/releases/download/v0.1.0/htmldiff_Darwin_arm64.tar.gz"
      sha256 "9d2c8c1a2ac503af53c00601335d2aecd6b74ce2f5a90a0c28324e22fdb1d88e"

      def install
        bin.install "htmldiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/htmldiff/releases/download/v0.1.0/htmldiff_Darwin_x86_64.tar.gz"
      sha256 "7cb13fc9a1731d73eb65078741905df5fb2a91363e7bb89937e365131a345a24"

      def install
        bin.install "htmldiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/htmldiff/releases/download/v0.1.0/htmldiff_Linux_x86_64.tar.gz"
      sha256 "067632f96eecd6b0527c6d4d3846d39262abda21a20e615fabd7551cd4db996f"

      def install
        bin.install "htmldiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/htmldiff/releases/download/v0.1.0/htmldiff_Linux_arm64.tar.gz"
      sha256 "3074a1183b29278136aa92ec9fbe92c74409469cc5902a3206346f8b87346f06"

      def install
        bin.install "htmldiff"
      end
    end
  end
end
