# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iawc < Formula
  desc "This tool check and report inappropriate words in your documents."
  homepage "https://github.com/kemokemo/iawc"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/iawc/releases/download/v0.0.1/iawc_Darwin_x86_64.tar.gz"
      sha256 "5010693901a8b36917668d9fbce1171c35b82e22811f73a57d14f2d584382cd7"

      def install
        bin.install "iawc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/iawc/releases/download/v0.0.1/iawc_Darwin_arm64.tar.gz"
      sha256 "ef59e769bf01ab26eaea18827792239ebb06e98dd4848889066c7f8a79326bcc"

      def install
        bin.install "iawc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/iawc/releases/download/v0.0.1/iawc_Linux_x86_64.tar.gz"
      sha256 "097f084d5b22627e6cab7620ef53aa1dd5d36f113c099668db7db4c229488574"

      def install
        bin.install "iawc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/iawc/releases/download/v0.0.1/iawc_Linux_arm64.tar.gz"
      sha256 "15b7ff4b486ed8fe7227898c15543b0b04a6dc6e02b16b11eb84099dd3b30442"

      def install
        bin.install "iawc"
      end
    end
  end
end
