# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgdiff < Formula
  desc "This tool compares old and new versions of image files and generates color-coded image in a diff format."
  homepage "https://github.com/kemokemo/imgdiff"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kemokemo/imgdiff/releases/download/v0.1.0/imgdiff_Darwin_arm64.tar.gz"
      sha256 "1b86d9f39dfcfb047ba691f922a2227af84777ce222985b93b75b1a638530b85"

      def install
        bin.install "imgdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/imgdiff/releases/download/v0.1.0/imgdiff_Darwin_x86_64.tar.gz"
      sha256 "f4adb138788edb0a4f50f675ebe2a7078a191c3fb476ae34668c9203187fb5e8"

      def install
        bin.install "imgdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kemokemo/imgdiff/releases/download/v0.1.0/imgdiff_Linux_arm64.tar.gz"
      sha256 "b93bf243a5100753a5d32dc32e099a439b3fbf6ef0d6240b14ccd808b4431e0c"

      def install
        bin.install "imgdiff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kemokemo/imgdiff/releases/download/v0.1.0/imgdiff_Linux_x86_64.tar.gz"
      sha256 "df6d8056a2db34b9d508788de674b9ecf47d3c68cd02b4eb25e22b8c2a465133"

      def install
        bin.install "imgdiff"
      end
    end
  end
end
